openapi: 3.0.2
info:
  version: 1.0.0
  title: title
paths:
  "/Customer":
    post:
      tags:
      - Customer
      summary: Add or update product master data
      description: ''
      operationId: addUpdate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/Customer"
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/CustomerResponse"
        '405':
          description: Invalid input
components:
  schemas:
    Customer:
      type: object
      description: The representation of a product master data (stamdata).
      properties:
        id:
          type: integer
          readOnly: true
          description: A unique entry ID
        name:
          type: string
          maxLength: 255
          nullable: true
          description: Name of product
        customerno:
          type: string
          nullable: false
          description: Product id
    CustomerResponse:
      type: object
      description: The representation of product master data (response).
      properties:
        content:
          "$ref": "#/components/schemas/Customer"
        status:
          type: string
