openapi: 3.0.2
info:
  version: 1.0.0
  title: title
paths:
  "/Product":
    post:
      tags:
      - Product
      summary: Add or update product master data
      description: ''
      operationId: addUpdate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/Product"
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ProductResponse"
        '405':
          description: Invalid input
components:
  schemas:
    Product:
      type: object
      description: The representation of a product master data (stamdata).
      properties:
        id:
          type: integer
          readOnly: true
          description: A unique entry ID
        title:
          type: string
          maxLength: 255
          nullable: true
          description: Name of product
        productno:
          type: string
          nullable: false
          description: Product id
        barcode:
          type: string
          nullable: true
          description: Barcode
        brand:
          type: string
          maxLength: 100
          nullable: true
          description: Brand
        suggestedprice:
          type: number
          nullable: true
          format: double
          description: The suggested price
        price:
          type: number
          nullable: true
          format: double
          description: The actual price
        color:
          type: string
          maxLength: 255
          nullable: true
          description: Color
        size:
          type: string
          maxLength: 255
          nullable: true
          description: Size
        vat:
          type: number
          nullable: true
          format: double
          Product: '25'
          description: VAT in percent
        industry:
          type: string
          maxLength: 255
          nullable: false
          readOnly: true
          Product: bikeshop
          description: 'Industry. Products: bikeshop, garden, phone, jewelry, generic.'
        country:
          type: string
          maxLength: 255
          nullable: false
          readOnly: false
          Product: dk
          description: 'Country. Products: dk, en.'
        year:
          type: string
          nullable: true
          Product: 2019
          description: Year
        lastupdate:
          type: string
          maxLength: 255
          nullable: false
          readOnly: true
          description: Date time of the last time this entry was updated
    ProductResponse:
      type: object
      description: The representation of product master data (response).
      properties:
        content:
          "$ref": "#/components/schemas/Product"
        status:
          type: string
